### ISSUE TITLE
Poser is broken

### ISSUE THREAD

**Issue by russianlagman** [PUGX/badge-poser#228]
Serving of badges is currently broken: https://poser.pugx.org/

```
exception 'Predis\ServerException' with message 'MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.' in /var/www/bp/badge-poser3/vendor/predis/predis/lib/Predis/Client.php:282 Stack trace: #0 /var/www/bp/badge-poser3/vendor/predis/predis/lib/Predis/Client.php(250): Predis\Client->onResponseError(Object(Predis\Command\StringIncrement), Object(Predis\ResponseError)) #1 /var/www/bp/badge-poser3/vendor/predis/predis/lib/Predis/Client.php(228): Predis\Client->executeCommand(Object(Predis\Command\StringIncrement)) #2 /var/www/bp/badge-poser3/src/PUGX/StatsBundle/Service/RedisPersister.php(62): Predis\Client-> call('incr', Array) #3 /var/www/bp/badge-poser3/src/PUGX/StatsBundle/Service/RedisPersister.php(62): Predis\Client->incr('STAT.TOTAL') #4 /var/www/bp/badge-poser3/src/PUGX/StatsBundle/Listener/StatsListener.php(75): PUGX\StatsBundle\Service\RedisPersister->incrementTotalAccess() #5 /var/www/bp/badge-poser3/src/PUGX/StatsBundle/Listener/StatsListener.php(45): PUGX\StatsBundle\Listener\StatsListener->persistData(Object(Symfony\Component\HttpFoundation\Request), 'versionAction') #6 [internal function]: PUGX\StatsBundle\Listener\StatsListener->onKernelController(Object(Symfony\Component\HttpKernel\Event\FilterControllerEvent), 'kernel.controll...', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher)) #7 /var/www/bp/badge-poser3/app/cache/prod/classes.php(1782): call user func(Array, Object(Symfony\Component\HttpKernel\Event\FilterControllerEvent), 'kernel.controll...', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher)) #8 /var/www/bp/badge-poser3/app/cache/prod/classes.php(1700): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.controll...', Object(Symfony\Component\HttpKernel\Event\FilterControllerEvent)) #9 /var/www/bp/badge-poser3/app/bootstrap.php.cache(3208): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.controll...', Object(Symfony\Component\HttpKernel\Event\FilterControllerEvent)) #10 /var/www/bp/badge-poser3/app/bootstrap.php.cache(3173): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #11 /var/www/bp/badge-poser3/app/bootstrap.php.cache(3324): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #12 /var/www/bp/badge-poser3/app/bootstrap.php.cache(2514): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #13 /var/www/bp/badge-poser3/web/app.php(18): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 {main}
exception 'Predis\ServerException' with message 'MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.' in /var/www/bp/badge-poser3/vendor/predis/predis/lib/Predis/Client.php:282 Stack trace: #0 /var/www/bp/badge-poser3/vendor/predis/predis/lib/Predis/Client.php(250): Predis\Client->onResponseError(Object(Predis\Command\StringIncrement), Object(Predis\ResponseError)) #1 /var/www/bp/badge-poser3/vendor/predis/predis/lib/Predis/Client.php(228): Predis\Client->executeCommand(Object(Predis\Command\StringIncrement)) #2 /var/www/bp/badge-poser3/src/PUGX/StatsBundle/Service/RedisPersister.php(62): Predis\Client-> call('incr', Array) #3 /var/www/bp/badge-poser3/src/PUGX/StatsBundle/Service/RedisPersister.php(62): Predis\Client->incr('STAT.TOTAL') #4 /var/www/bp/badge-poser3/src/PUGX/StatsBundle/Listener/StatsListener.php(75): PUGX\StatsBundle\Service\RedisPersister->incrementTotalAccess() #5 /var/www/bp/badge-poser3/src/PUGX/StatsBundle/Listener/StatsListener.php(45): PUGX\StatsBundle\Listener\StatsListener->persistData(Object(Symfony\Component\HttpFoundation\Request), 'versionAction') #6 [internal function]: PUGX\StatsBundle\Listener\StatsListener->onKernelController(Object(Symfony\Component\HttpKernel\Event\FilterControllerEvent), 'kernel.controll...', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher)) #7 /var/www/bp/badge-poser3/app/cache/prod/classes.php(1782): call user func(Array, Object(Symfony\Component\HttpKernel\Event\FilterControllerEvent), 'kernel.controll...', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher)) #8 /var/www/bp/badge-poser3/app/cache/prod/classes.php(1700): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.controll...', Object(Symfony\Component\HttpKernel\Event\FilterControllerEvent)) #9 /var/www/bp/badge-poser3/app/bootstrap.php.cache(3208): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.controll...', Object(Symfony\Component\HttpKernel\Event\FilterControllerEvent)) #10 /var/www/bp/badge-poser3/app/bootstrap.php.cache(3173): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #11 /var/www/bp/badge-poser3/app/bootstrap.php.cache(3324): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #12 /var/www/bp/badge-poser3/app/bootstrap.php.cache(2514): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #13 /var/www/bp/badge-poser3/web/app.php(18): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 {main}
generic
generic
```

**Comment by JellyBellyDev** [comment]
We have fixed the problem on the systems side.
Thanks for the report. 👍
