### ISSUE TITLE
Redis error in badge

### ISSUE THREAD

**Issue by mtk3d** [PUGX/badge-poser#260]
There is an error in lumen bagde: https://poser.pugx.org/laravel/lumen-framework/d/total.svg
```
exception 'Predis\ServerException' with message 'MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.' in /var/www/bp/badge-poser3/vendor/predis/predis/lib/Predis/Client.php:282
Stack trace:
#0 /var/www/bp/badge-poser3/vendor/predis/predis/lib/Predis/Client.php(250): Predis\Client-&gt;onResponseError(Object(Predis\Command\StringIncrement), Object(Predis\ResponseError))
#1 /var/www/bp/badge-poser3/vendor/predis/predis/lib/Predis/Client.php(228): Predis\Client-&gt;executeCommand(Object(Predis\Command\StringIncrement))
#2 /var/www/bp/badge-poser3/src/PUGX/StatsBundle/Service/RedisPersister.php(62): Predis\Client-&gt; call('incr', Array)
#3 /var/www/bp/badge-poser3/src/PUGX/StatsBundle/Service/RedisPersister.php(62): Predis\Client-&gt;incr('STAT.TOTAL')
#4 /var/www/bp/badge-poser3/src/PUGX/StatsBundle/Listener/StatsListener.php(75): PUGX\StatsBundle\Service\RedisPersister-&gt;incrementTotalAccess()
#5 /var/www/bp/badge-poser3/src/PUGX/StatsBundle/Listener/StatsListener.php(45): PUGX\StatsBundle\Listener\StatsListener-&gt;persistData(Object(Symfony\Component\HttpFoundation\Request), 'downloadsAction')
#6 [internal function]: PUGX\StatsBundle\Listener\StatsListener-&gt;onKernelController(Object(Symfony\Component\HttpKernel\Event\FilterControllerEvent), 'kernel.controll...', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#7 /var/www/bp/badge-poser3/app/cache/prod/classes.php(1782): call user func(Array, Object(Symfony\Component\HttpKernel\Event\FilterControllerEvent), 'kernel.controll...', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#8 /var/www/bp/badge-poser3/app/cache/prod/classes.php(1700): Symfony\Component\EventDispatcher\EventDispatcher-&gt;doDispatch(Array, 'kernel.controll...', Object(Symfony\Component\HttpKernel\Event\FilterControllerEvent))
#9 /var/www/bp/badge-poser3/app/bootstrap.php.cache(3208): Symfony\Component\EventDispatcher\EventDispatcher-&gt;dispatch('kernel.controll...', Object(Symfony\Component\HttpKernel\Event\FilterControllerEvent))
#10 /var/www/bp/badge-poser3/app/bootstrap.php.cache(3173): Symfony\Component\HttpKernel\HttpKernel-&gt;handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#11 /var/www/bp/badge-poser3/app/bootstrap.php.cache(3324): Symfony\Component\HttpKernel\HttpKernel-&gt;handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#12 /var/www/bp/badge-poser3/app/bootstrap.php.cache(2514): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel-&gt;handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#13 /var/www/bp/badge-poser3/web/app.php(18): Symfony\Component\HttpKernel\Kernel-&gt;handle(Object(Symfony\Component\HttpFoundation\Request))
#14 {main}
```
<img width="1231" alt="Zrzut ekranu 2019-05-28 o 11 39 24" src="https://user-images.githubusercontent.com/12657846/58468169-59238900-813d-11e9-8f3e-f66ec177c8e8.png">

**Comment by JellyBellyDev** [comment]
Now works! Right?

**Comment by JellyBellyDev** [comment]
it must have been a temporary problem.

**Comment by mtk3d** [comment]
Yup, it's work now, thanks

**Comment by mtk3d** [comment]
It's still doesn't work properly: https://poser.pugx.org/laravel/lumen-framework/d/total.svg
<img width="974" alt="Zrzut ekranu 2019-06-3 o 14 26 03" src="https://user-images.githubusercontent.com/12657846/58801690-8bd0f400-860b-11e9-9d2f-c3a2c0a0477c.png">

**Comment by peter-gribanov** [comment]
I had a similar problem a few minutes ago. Now all is good.
But you still need disable a error reporting.
https://poser.pugx.org/happyr/doctrine-specification/v/stable.svg
![image](https://user-images.githubusercontent.com/1954436/58862747-0bb59780-86ba-11e9-994f-d45afe43423b.png)

**Comment by JellyBellyDev** [comment]
We know, we are working hard on the new version of badge-poser where we won't have these problems! ;)
