### ISSUE TITLE
Poser is broken :(

### ISSUE THREAD

**Issue by kwn** [PUGX/badge-poser#266]
Hi guys, first of all thank you for the great work. 

Today I found out that Poser is broken. Instead of the bade it generates:

```
exception 'Predis\ServerException' with message 'MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.' in /var/www/bp/badge-poser3/vendor/predis/predis/lib/Predis/Client.php:282 Stack trace: #0 /var/www/bp/badge-poser3/vendor/predis/predis/lib/Predis/Client.php(250): Predis\Client->onResponseError(Object(Predis\Command\StringIncrement), Object(Predis\ResponseError)) #1 /var/www/bp/badge-poser3/vendor/predis/predis/lib/Predis/Client.php(228): Predis\Client->executeCommand(Object(Predis\Command\StringIncrement)) #2 /var/www/bp/badge-poser3/src/PUGX/StatsBundle/Service/RedisPersister.php(62): Predis\Client-> call('incr', Array) #3 /var/www/bp/badge-poser3/src/PUGX/StatsBundle/Service/RedisPersister.php(62): Predis\Client->incr('STAT.TOTAL') #4 /var/www/bp/badge-poser3/src/PUGX/StatsBundle/Listener/StatsListener.php(75): PUGX\StatsBundle\Service\RedisPersister->incrementTotalAccess() #5 /var/www/bp/badge-poser3/src/PUGX/StatsBundle/Listener/StatsListener.php(45): PUGX\StatsBundle\Listener\StatsListener->persistData(Object(Symfony\Component\HttpFoundation\Request), 'versionAction') #6 [internal function]: PUGX\StatsBundle\Listener\StatsListener->onKernelController(Object(Symfony\Component\HttpKernel\Event\FilterControllerEvent), 'kernel.controll...', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher)) #7 /var/www/bp/badge-poser3/app/cache/prod/classes.php(1782): call user func(Array, Object(Symfony\Component\HttpKernel\Event\FilterControllerEvent), 'kernel.controll...', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher)) #8 /var/www/bp/badge-poser3/app/cache/prod/classes.php(1700): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.controll...', Object(Symfony\Component\HttpKernel\Event\FilterControllerEvent)) #9 /var/www/bp/badge-poser3/app/bootstrap.php.cache(3208): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.controll...', Object(Symfony\Component\HttpKernel\Event\FilterControllerEvent)) #10 /var/www/bp/badge-poser3/app/bootstrap.php.cache(3173): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #11 /var/www/bp/badge-poser3/app/bootstrap.php.cache(3324): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #12 /var/www/bp/badge-poser3/app/bootstrap.php.cache(2514): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #13 /var/www/bp/badge-poser3/web/app.php(18): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 {main}
```

Analysing the stack trace it looks like you run out of a hard drive space, so Redis cannot persist its cache. Thank you in advance for fix it!

**Comment by Moskito89** [comment]
And also the website tells for every package "Repository not found!". This is how it looks like:
![Bildschirmfoto 2019-07-04 um 09 27 20](https://user-images.githubusercontent.com/6805697/60647400-eee9bc80-9e3d-11e9-9405-57e000a39e75.png)

**Comment by nick-zh** [comment]
I experience the same, any insight on this @liuggio ?

**Comment by AlessandroMinoccheri** [comment]
It seems that know all is solved right?

**Comment by kwn** [comment]
Looks good now! Thank you guys!
